### PR TITLE
Add cheat for documented but not visible negative and merged filters.

### PR DESCRIPTION
**Pull request by jrafanie**
These are documented [here](https://help.github.com/articles/searching-issues/) but it's not obvious from github's user interface and some people may not know these things are possible.

### CODE REVIEW

**Comment by tiimgreen** [comment]
Thanks for your contribution @jrafanie, a few suggestions though. I think the first title should be called simply 'Filters' to avoid confusion. Also, I think the 'Merged pull requests filter' header is unnecessary and should just be put under the Filters title.

**Comment by tiimgreen** [comment]
@jrafanie any update on this? Would be nice to merge.

**Comment by jrafanie** [comment]
Thanks @tiimgreen, missed the prior notification, I'll submit your suggestions shortly.

**Comment by jrafanie** [comment]
@tiimgreen Fixed, also added the recent filtering by API status.  Let me know if you want them squashed.

Thanks!

**Comment by tiimgreen** [comment]
@jrafanie looks good, just one last thing `Read more about searching issues.` is duplicated. Could you remove the first one?

**Comment by jrafanie** [comment]
Thanks @tiimgreen, updated.

**Comment by tiimgreen** [comment]
Awesome, thanks :+1:

**Comment by jrafanie** [comment]
My pleasure, thank you!  :sunglasses:

**Pull request merged**
