### PR TITLE
Remove ignore whitespace

### PR DESCRIPTION
**Pull request by jfountain**
Unfortunately github seems to have discontinued the '?w=1' whitespace hiding feature. Noticed this about a week ago.

### CODE REVIEW

**Comment by bobthecow** [comment]
It still works on commit page diffs (for example, see https://github.com/dkim1116/github-cheat-sheet/commit/a0162699748806851b5a24473304b1aee161db95?w=1 from #154)

**Comment by hkdobrev** [comment]
I think they just didn't implement everything in the new PR commit pages. For example `.diff` and `.patch` links there are not working either, but working on the canonical commit URLs.

**Comment by jfountain** [comment]
Interesting that it's not consistent. I'm going to contact github support directly on this. It may have been a regression bug on the new PR pages. Or maybe the feature is going to be removed on all diff pages. Either way I'll close this for now and re-open depending on feedback from github.

**Comment by jfountain** [comment]
I heard back from Github on this and they turned the feature back on for pull requests. All rejoice! Thanks @rsese

**Comment by tiimgreen** [comment]
Awesome, thanks!

**Pull request closed without merging**
