### PR TITLE
Adding SSH key trick

### PR DESCRIPTION
**Pull request by sieben**
SSH key trick

### CODE REVIEW

**Comment by yang-wei** [comment]
+1

**Comment by tiimgreen** [comment]
Nice tip @sieben, just a few things that need correcting:

In the menu it should be `- [SSH keys](#ssh-keys)`, with a dash to ensure the link works correctly.

To make it easier to understand, try adding a brief description before the example and change the text to a generic example.

Also, I've added a relevant link in there, it's not strictly documentation but I feel it could be useful for some people.

This could work:


    You can get a list of public ssh keys in plain text format by visiting:
    
    ```
    https://github.com/{user}.keys
    ```
    
    e.g. [https://github.com/tiimgreen.keys](https://github.com/tiimgreen.keys)

    [Read more about accessing public ssh keys...](https://changelog.com/github-exposes-public-ssh-keys-for-its-users/)

**Comment by sieben** [comment]
@tiimgreen Done :)

**Comment by tiimgreen** [comment]
Thanks for the speedy reply, merged! :+1:

**Pull request merged**
